[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "isp_churn"
version = "0.0.1"
description = "End to End Mlops"
authors = [
  { name = "islam" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"
dependencies = [
    "black>=26.5.1",
    "dagshub>=0.7.2",
    "dvc>=3.67.1",
    "fastapi[standard]>=0.141.1",
    "kagglehub>=1.0.2",
    "loguru>=0.7.3",
    "mlflow>=3.16.0",
    "optuna>=5.0.0",
    "pandas>=2.3.3",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "typer>=0.27.2",
    "uvicorn>=0.52.4",
    "xgboost>=3.2.0",
]

[tool.flit.module]
name = "src"

[tool.ruff]
line-length = 99
src = ["src"]
include = ["pyproject.toml", "src/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["src"]
force-sort-within-sections = true

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

